In [1]:
#import numpy:
import numpy as np

In [2]:
np.random.seed(0) #seed for reproducibility

In [3]:
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [4]:
x1
#vector of size 6 containing elements <=10

array([5, 0, 3, 3, 7, 9])

In [5]:
x2
#matrix of shape 3*4 containing elements <=10

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [6]:
#each array has 3 attributes:
print("ndim of x3: ", x3.ndim) #ndim: number of dimensions (in this case=3)
print("shape of x3: ", x3.shape) #size of each dimension
print("total size of x3: ", x3.size) #total size

ndim of x3:  3
shape of x3:  (3, 4, 5)
total size of x3:  60


In [7]:
#another property is data type:
print("data type of element of x2: ", x2.dtype)

data type of element of x2:  int64


In [8]:
#Array slicing:

In [9]:
#One dimensional:
x = np.arange(10)

print(x[:5]) #first 5 elements
print(x[5:]) #elements from index 5
print(x[4:7]) #sub-array (from 4->6, no 7!!)

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]


In [10]:
x[::3]
#strat from first element and advance with step=3

array([0, 3, 6, 9])

In [11]:
x[2::3]
#from element with index 2 (3d element) and advance with step=3

array([2, 5, 8])

In [12]:
x[1::2]

array([1, 3, 5, 7, 9])

In [13]:
#Multi-dimension:
print(x2[:,0]) #first column
#equivalent to x2[0]

[3 7 1]


In [14]:
print(x2[1,:]) #second row

[7 6 8 8]


In [15]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [16]:
#Reshaping:
array = np.arange(1, 10)

matrix = array.reshape((3,3))
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
matrix2 = array.reshape((2,2))
#this method recognizes the size of the array!!
#so can not reshape array of size 9 into matrix (3,3)

ValueError: cannot reshape array of size 9 into shape (2,2)

In [18]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [19]:
w = v.reshape((3,1))
w

array([[1],
       [2],
       [3]])

In [20]:
w2 = v.reshape(-1,1)
w2

array([[1],
       [2],
       [3]])

In [22]:
vec_x2 = x2.reshape(-1,1) #transform matrix into vector
print(x2)
vec_x2

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([[3],
       [5],
       [2],
       [4],
       [7],
       [6],
       [8],
       [8],
       [1],
       [6],
       [7],
       [7]])

In [24]:
mat_x2 = vec_x2.reshape((5,3))
mat_x2
#sizes must much (not less and not more !!)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [25]:
#Concatenation of arrays:

In [26]:
#One dim:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x, y]))

z = np.array([5,6])
print(np.concatenate([x,z,y]))

[1 2 3 3 2 1]
[1 2 3 5 6 3 2 1]


In [29]:
#2 dim:
grid1 = np.array([[1,2,3], [3,4,5]])
grid2 = np.array([[9,8,7], [7,6,0]])

print(grid1)
print(grid2)
print(np.concatenate([grid1, grid2]))
print(np.concatenate([grid1, grid2], axis=1))

[[1 2 3]
 [3 4 5]]
[[9 8 7]
 [7 6 0]]
[[1 2 3]
 [3 4 5]
 [9 8 7]
 [7 6 0]]
[[1 2 3 9 8 7]
 [3 4 5 7 6 0]]


In [30]:
#Splitting arrays:

In [31]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [32]:
x1, x2, x3 = np.split(x, [2, 5])
print(x1,x2,x3)

[1 2] [ 3 99 99] [3 2 1]


In [35]:
x1, x2, x3 = np.split(x, [7, 7])
print(x1,x2,x3)

[ 1  2  3 99 99  3  2] [] [1]
