In [1]:
import numpy as np

In [2]:
#Computation on NumPy arrays can be very fast using "vectorized operations", implemented by 
# Universal Functions "ufuncs"

In [5]:
np.random.seed(0)
values = np.random.randint(1, 10, size=5) #vector of size 5, containing random values <10

print(values)
print(1.0 / values) #element-wise inverse

[6 1 4 4 8]
[0.16666667 1.         0.25       0.25       0.125     ]


In [7]:
%timeit (1.0 / values)
#big advantage of ufuns is fast execution

1.06 µs ± 21.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
x = np.arange(4)
print("x=",x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) #floor division

x= [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [11]:
np.add(x, 2) #eq= x + 2 (element-wise)

array([2, 3, 4, 5])

In [12]:
print("3^x=", np.power(3, x))

3^x= [ 1  3  9 27]


In [14]:
y = [1, 2, 4, 10]
print("log2(y)= ", np.log2(y))

print("log10(y)= ", np.log10(y))

log2(y)=  [0.         1.         2.         3.32192809]
log10(y)=  [0.         0.30103    0.60205999 1.        ]


In [15]:
#some aggregates:
x = np.arange(1, 6)
np.add.reduce(x) #will output the sum of all elements

15

In [16]:
np.multiply.reduce(x) #will give the result of multiplying all elements

120

In [17]:
np.add.accumulate(x) #store results of intermidiate values

array([ 1,  3,  6, 10, 15])

In [18]:
#Numpy version is always faster:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

85.1 ms ± 1.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
526 µs ± 45.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [19]:
%timeit min(big_array)
%timeit np.min(big_array)

71.3 ms ± 3.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
553 µs ± 28.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
#Multi-dim aggregates:
M = np.random.random((3, 4))
print(M)

[[0.85541154 0.27965023 0.95573175 0.03659582]
 [0.60934925 0.59753225 0.07463842 0.43803321]
 [0.21812627 0.53159247 0.10793176 0.8448757 ]]


In [22]:
print(np.sum(M))
M.sum()

5.549468678228611


5.549468678228611

In [23]:
%timeit np.sum(M)
%timeit M.sum()

3.04 µs ± 36.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.29 µs ± 51.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [25]:
M.min() #absolute min

0.0365958240427009

In [27]:
M.min(axis=0) #minimum values over horizental line

array([0.21812627, 0.27965023, 0.07463842, 0.03659582])

In [28]:
M.max(axis=1) #max over verticzl line

array([0.95573175, 0.60934925, 0.8448757 ])