In [1]:
#import numpy:
import numpy as np #np is alias

In [3]:
np?

'''
Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

'''

'\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\n'

In [5]:
#Python is dynamically typed language:

x = 4 #x interpreted as int
print(type(x))
x = "four" #x interpreted as string
print(type(x))

<class 'int'>
<class 'str'>


In [7]:
#fixed type-array:

import array
L = list(range(10))
A = array.array('i', L)
print(type(L))
print(type(A))
A

<class 'list'>
<class 'array.array'>


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#creating arrays using np.array:
np.array([1, 2, 3, 5, 4])

array([1, 2, 3, 5, 4])

In [10]:
#if types do not match => upcast if possible:
np.array([1, 3.14, 2, 5])
#integers will be upcasted to float

array([1.  , 3.14, 2.  , 5.  ])

In [12]:
np.array([5, "c", 2, "b"])
#integers will be upcasted to string

array(['5', 'c', '2', 'b'], dtype='<U21')

In [14]:
np.array([5.2, "c", 2, "b"])
#upcasted to float

array(['5.2', 'c', '2', 'b'], dtype='<U32')

In [17]:
#creating arrays from scratch:
np.zeros(10, dtype=int)
#vector of length 10 containing only "0"

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones((3,5), dtype=float)
#(3*5)matrix containing "1"

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.full((2,3), 5.5)
#(2*3) matrix full of value "5.5"

array([[5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5]])

In [23]:
np.arange(0,20,2)
#array from 0=>20 step:2 (excluding 20)
# !!! stops at "18" !!!

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.linspace(0,1,5)
#array of 5 values evenly spaced between 0 and 1 (including 0 and 1)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.random.random((3,3))

array([[0.95494707, 0.81224906, 0.09437082],
       [0.89439149, 0.25336513, 0.32663738],
       [0.17741503, 0.30322277, 0.30061053]])