In [1]:
import numpy as np

In [3]:
a = np.array([0,1,2]) #eq: a = np.arange(3)
a

array([0, 1, 2])

In [5]:
a + 2 #element-wise adding ("2" will be broadcasted)

array([2, 3, 4])

In [6]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
M + a #a will be broadcasted

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [10]:
b = np.array([0,2])
M + b #can NOT broadcast "b", no matching in shapes

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [12]:
a + b #also error !!

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [13]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [14]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [15]:
#Indexing :

In [16]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [18]:
ind = [3, 7, 4]
x[ind] #return array of elements with indexes 3 (4th element), 7 and 4

array([71, 86, 60])

In [19]:
ind = np.array([[3, 7],[4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [20]:
#sorting:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [21]:
i = np.argsort(x) #vector containing indexes of first smallest element, then the second smallest and so on ...
print(i)

[1 0 3 2 4]
